### PR TITLE
Swim in meters

### PR DESCRIPTION
**Pull request by gmiossec29**
Even with units settings in kilometer, swim activities were displayed in yards

### CODE REVIEW

**Comment by dblock** [comment]
Amazing! Thank you.

**Comment by dblock** [comment]
Btw those user tests aren’t failing for me either way, so probably order dependent. The find method gets a user from the database and then does user info from slack to update the data. The (more) correct fix is to make the username something like “whatever” so that it doesn’t ever find an existing record, and creates a new one. I’ll take care of it later ...

**Comment by dblock** [comment]
I don’t have computer access today (traveling) but will deploy this tomorrow.

**Comment by gmiossec29** [comment]
You are welcome !

**Comment by dblock** [comment]
Are you using the bot? I’ll subscribe you for free if you want (what’s your team ID?).

**Comment by gmiossec29** [comment]
Yes, we are using the bot on a shared slack : velochinois.slack.com
Thanks you very much for your offer ! Our team ID is T8UBG68RZ. 
If I can I would be happy to contribute again to your project !

**Comment by dblock** [comment]
Upgraded, this won't expire. Don't hesitate to [donate to TeamForKids](https://runwithtfk.org/Profile/PublicPage/61018) if you find the bot useful and thanks for contributing code!

**Comment by gmiossec29** [comment]
Thank you very much !

**Pull request merged**
